"""
=============================================================================
  MEDICAL RAG PIPELINE — Stage 4: Production Abstract Embedding Generator
=============================================================================
  Input  : chunks.json (generated by Stage 3 Semantic Chunk Builder)
  Output : embeddings.json (Vector embeddings + full metadata per chunk)
=============================================================================
"""

from __future__ import annotations

import os
import sys
import json
import math
import time
import logging
import hashlib
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional, Tuple, Set

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..")))

from rag_system.embeddings import BaseEmbedder, CohereEmbedder, FastEmbedEmbedder, OllamaEmbedder
from rag_system.config.config import (
    DEFAULT_CHUNKS_JSON,
    DEFAULT_EMBEDDINGS_JSON,
    COHERE_API_KEY,
    COHERE_EMBED_MODEL,
    EMBEDDING_DIMENSION
)

# Initialize Logger
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler(sys.stdout)]
)
logger = logging.getLogger("EmbeddingPipeline")


@dataclass
class EmbeddedRecord:
    """Complete embedded record format matching Vector DB output schema."""
    chunk_id: str
    embedding: List[float]
    metadata: Dict[str, Any]
    content: str
    table_references: List[str] = field(default_factory=list)
    figure_references: List[Dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "chunk_id": self.chunk_id,
            "embedding": self.embedding,
            "metadata": self.metadata,
            "content": self.content,
            "table_references": self.table_references,
            "figure_references": self.figure_references
        }


def compute_content_hash(content: str) -> str:
    """Generates SHA-256 digest of chunk text for content modification detection."""
    return hashlib.sha256(content.strip().encode("utf-8")).hexdigest()


def construct_embedding_text(chunk: dict) -> str:
    """Constructs hierarchical text representation before embedding generation."""
    header_parts = []
    doc_title = chunk.get("document_title", "").strip()
    chapter = chunk.get("chapter", "").strip()
    section = chunk.get("section", "").strip()
    subsection = chunk.get("subsection", "").strip()

    if doc_title:
        header_parts.append(f"Document: {doc_title}")
    if chapter:
        header_parts.append(f"Chapter: {chapter}")
    if section:
        header_parts.append(f"Section: {section}")
    if subsection:
        header_parts.append(f"Subsection: {subsection}")

    hierarchy_prefix = "\n".join(header_parts)
    content = chunk.get("content", "").strip()

    return f"{hierarchy_prefix}\n\nContent:\n{content}".strip()


class EmbeddingPipeline:
    """Production Embedding Pipeline leveraging the BaseEmbedder architecture."""

    def __init__(self, embedder: Optional[BaseEmbedder] = None):
        # Initialize embedder using configuration, prioritizing Cohere API
        if embedder:
            self.embedder = embedder
        else:
            api_key = COHERE_API_KEY or os.environ.get("COHERE_API_KEY", "").strip()
            if api_key:
                logger.info(f"Initializing Cohere API embedder with model '{COHERE_EMBED_MODEL}'...")
                self.embedder = CohereEmbedder(api_key=api_key, model=COHERE_EMBED_MODEL)
            else:
                logger.warning("COHERE_API_KEY environment variable not found. Falling back to local offline FastEmbed (BAAI/bge-small-en-v1.5)...")
                self.embedder = FastEmbedEmbedder()
        
        self.expected_dimension = self.embedder.dimension
        self.batch_size = 32

    def run(self) -> List[EmbeddedRecord]:
        start_time = time.time()
        logger.info(f"Starting Embedding Pipeline (Expected Dimension: {self.expected_dimension})...")

        # 1. Load input chunks
        if not os.path.exists(DEFAULT_CHUNKS_JSON):
            raise FileNotFoundError(f"Input chunks file not found: {DEFAULT_CHUNKS_JSON}")

        with open(DEFAULT_CHUNKS_JSON, "r", encoding="utf-8") as f:
            raw_chunks = json.load(f)

        logger.info(f"Loaded {len(raw_chunks)} chunks from {DEFAULT_CHUNKS_JSON}.")
        chunk_map = {c["chunk_id"]: c for c in raw_chunks}

        # 2. Resume Validation & Self-Healing
        existing_records, valid_existing_records = self._load_and_validate_existing(chunk_map)
        logger.info(f"Resumability: {len(valid_existing_records)} / {len(raw_chunks)} records validated from cache.")

        valid_ids = {r.chunk_id for r in valid_existing_records}
        remaining_chunks = [c for c in raw_chunks if c["chunk_id"] not in valid_ids]
        
        embedded_records: List[EmbeddedRecord] = list(valid_existing_records)
        total_chunks = len(raw_chunks)
        processed_count = len(valid_existing_records)
        failed_count = 0

        # 3. Batch Embedding Generation
        if remaining_chunks:
            logger.info(f"Generating embeddings for {len(remaining_chunks)} remaining chunk(s)...")
            
            for i in range(0, len(remaining_chunks), self.batch_size):
                batch_chunks = remaining_chunks[i : i + self.batch_size]
                batch_texts = [construct_embedding_text(c) for c in batch_chunks]

                try:
                    t_batch_start = time.time()
                    batch_embeddings = self.embedder.embed_documents(batch_texts)
                    batch_latency = time.time() - t_batch_start
                    logger.info(f"Processed batch of {len(batch_chunks)} items in {batch_latency:.2f}s.")
                except Exception as e:
                    logger.error(f"Failed to generate embeddings for batch: {e}")
                    failed_count += len(batch_chunks)
                    continue

                for j, chunk in enumerate(batch_chunks):
                    emb = batch_embeddings[j] if j < len(batch_embeddings) else None

                    if emb and len(emb) == self.expected_dimension:
                        # Preserve metadata
                        meta = {}
                        for k, v in chunk.items():
                            if k not in ("content", "embedding", "chunk_id", "table_references", "figure_references"):
                                meta[k] = v
                        meta["content_hash"] = compute_content_hash(chunk.get("content", ""))

                        rec = EmbeddedRecord(
                            chunk_id=chunk["chunk_id"],
                            embedding=emb,
                            metadata=meta,
                            content=chunk.get("content", ""),
                            table_references=chunk.get("table_references", []),
                            figure_references=chunk.get("figure_references", [])
                        )
                        embedded_records.append(rec)
                    else:
                        logger.error(f"Invalid embedding result for chunk ID: {chunk['chunk_id']}")
                        failed_count += 1

                    processed_count += 1
                    print(f"Embedding chunk {processed_count} / {total_chunks}")

                # Incremental save
                self._save_output(embedded_records)

        total_time = time.time() - start_time
        logger.info(f"Embedding pipeline finished in {total_time:.2f} seconds. (Failed: {failed_count})")
        return embedded_records

    def _load_and_validate_existing(self, chunk_map: Dict[str, dict]) -> Tuple[List[EmbeddedRecord], List[EmbeddedRecord]]:
        """Loads and strictly validates existing embeddings.json records against input chunks."""
        if not os.path.exists(DEFAULT_EMBEDDINGS_JSON):
            return [], []

        raw_existing = []
        try:
            with open(DEFAULT_EMBEDDINGS_JSON, "r", encoding="utf-8") as f:
                raw_existing = json.load(f)
        except Exception as e:
            logger.warning(f"Could not read existing embeddings file: {e}")
            return [], []

        valid_records = []
        seen_ids = set()

        for item in raw_existing:
            chk_id = item.get("chunk_id")
            emb = item.get("embedding")
            meta = item.get("metadata", {})
            content = item.get("content", "")

            # Verify chunk exists in current chunk output
            if not chk_id or chk_id not in chunk_map:
                continue

            # Skip duplicates
            if chk_id in seen_ids:
                continue
            seen_ids.add(chk_id)

            # Content Hash Match Check
            orig_chunk = chunk_map[chk_id]
            expected_hash = compute_content_hash(orig_chunk.get("content", ""))
            stored_hash = meta.get("content_hash", "")

            if stored_hash and stored_hash != expected_hash:
                continue

            # Vector dimension match check
            if not emb or not isinstance(emb, list) or len(emb) != self.expected_dimension:
                continue

            rec = EmbeddedRecord(
                chunk_id=chk_id,
                embedding=emb,
                metadata=meta,
                content=content,
                table_references=item.get("table_references", []),
                figure_references=item.get("figure_references", [])
            )
            valid_records.append(rec)

        return [EmbeddedRecord(**i) for i in raw_existing if "chunk_id" in i], valid_records

    def _save_output(self, records: List[EmbeddedRecord]) -> None:
        """Saves current record list to output JSON file."""
        os.makedirs(os.path.dirname(DEFAULT_EMBEDDINGS_JSON), exist_ok=True)
        dict_output = [r.to_dict() for r in records]
        with open(DEFAULT_EMBEDDINGS_JSON, "w", encoding="utf-8") as f:
            json.dump(dict_output, f, indent=2, ensure_ascii=False)


if __name__ == "__main__":
    pipeline = EmbeddingPipeline()
    pipeline.run()
